server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/api/auction/**
        - id: user-profile-service
          uri: lb://user-profile-service
          predicates:
            - Path=/api/users/**
        - id: payment-gateway-service
          uri: lb://payment-gateway-service
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
